"use client";
import { useMemo, useState } from "react";
import { BrandLogo, inputClass, PageHeader, Panel, Pill, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";

type Company = "Microsoft" | "Amazon" | "TCS" | "Infosys" | "Google";
const opportunities: { company: Company; role: string; location: string; mode: string; pay: string; left: string; match: number; skills: string[] }[] = [
  { company: "Microsoft", role: "Cloud Engineering Intern", location: "Remote", mode: "Remote", pay: "₹25,000/month", left: "3 days left", match: 92, skills: ["Azure", "Linux", "Python"] },
  { company: "Amazon", role: "SDE Intern", location: "Bengaluru", mode: "Hybrid", pay: "₹45,000/month", left: "5 days left", match: 88, skills: ["DSA", "Java", "AWS"] },
  { company: "TCS", role: "Network Engineer", location: "Mumbai", mode: "Onsite", pay: "₹6 LPA", left: "8 days left", match: 84, skills: ["Networking", "Linux"] },
  { company: "Infosys", role: "Systems Engineer Trainee", location: "Pune", mode: "Hybrid", pay: "₹4.5 LPA", left: "12 days left", match: 79, skills: ["Java", "SQL", "Communication"] },
];

export default function OpportunitiesPage() {
  const [query, setQuery] = useState(""); const [mode, setMode] = useState("All"); const [saved, setSaved] = useState<string[]>(["SDE Intern"]); const [filtersOpen, setFiltersOpen] = useState(true);
  const visible = useMemo(() => opportunities.filter(o => (mode === "All" || o.mode === mode) && `${o.company} ${o.role} ${o.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, mode]);
  const toggleSave = (role: string) => setSaved(s => s.includes(role) ? s.filter(x => x !== role) : [...s, role]);
  return <div className="mx-auto max-w-[1320px]"><PageHeader eyebrow="Discover" title="Where should I apply?" description="High-fit internships and roles, ranked around your skills, preferences, and career goals." action={<button className={primaryButton}>＋ Create job alert</button>} />
    <Panel className="mb-5 p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><span className="absolute left-4 top-3.5">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} className={`${inputClass} pl-11`} placeholder="Search roles, companies, or skills..." /></div><div className="flex gap-2">{["All", "Remote", "Hybrid", "Onsite"].map(x => <button key={x} onClick={() => setMode(x)} className={`${secondaryButton} ${mode === x ? "border-violet-500 bg-violet-500/10 text-violet-300" : ""}`}>{x}</button>)}<button onClick={() => setFiltersOpen(v => !v)} className={secondaryButton}>⚙ Filters</button></div></div>
      {filtersOpen && <div className="mt-4 grid gap-3 border-t border-slate-800 pt-4 sm:grid-cols-2 lg:grid-cols-5">{[["Company", "All companies"], ["Role", "All roles"], ["Package / Stipend", "Any range"], ["Location", "All locations"], ["Duration", "Any duration"]].map(([label, value]) => <label key={label} className="text-[11px] font-semibold text-slate-400">{label}<select className={`${inputClass} mt-1 py-2.5`} defaultValue={value}><option>{value}</option><option>Recommended</option><option>Actively hiring</option></select></label>)}</div>}
    </Panel>
    <div className="mb-5 grid gap-4 lg:grid-cols-[1.6fr_1fr]"><Panel className="p-5"><SectionTitle icon="🔥" title="Trending Companies" description="Companies students are exploring this week" /><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{(["Microsoft", "Amazon", "Google", "Infosys"] as Company[]).map((c, i) => <div key={c} className="rounded-xl border border-slate-800 bg-black/15 p-3"><BrandLogo company={c} /><p className="mt-3 text-sm font-bold">{c}</p><p className="mt-1 text-[11px] text-slate-400">{[18, 24, 12, 31][i]} open roles</p></div>)}</div></Panel><Panel className="p-5"><SectionTitle icon="⭐" title="Recommended For You" description="Based on your profile" /><div className="mt-5 flex items-center gap-3"><BrandLogo company="Microsoft" size={54} /><div><p className="text-sm font-bold">Cloud Engineering Intern</p><p className="text-xs text-slate-400">Excellent skill alignment</p></div><strong className="ml-auto text-emerald-400">92%</strong></div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-violet-600 to-emerald-400" /></div></Panel></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_280px]"><div><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">💼 Opportunities Feed <span className="ml-2 text-xs font-normal text-slate-500">{visible.length} matches</span></h2><select className="rounded-lg border border-slate-700 bg-[#0b0e14] px-3 py-2 text-xs"><option>Best match</option><option>Newest</option><option>Deadline</option></select></div><div className="space-y-3">{visible.map(o => <Panel key={o.role} className="p-5"><div className="flex flex-col gap-4 sm:flex-row"><BrandLogo company={o.company} size={56} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-bold">{o.role}</h3><p className="mt-1 text-sm text-slate-400">{o.company}</p></div><Pill tone="green">⭐ {o.match}% Match</Pill></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-400"><span>📍 {o.location}</span><span>💰 {o.pay}</span><span>🕒 {o.left}</span><span>◉ {o.mode}</span></div><div className="mt-3 flex flex-wrap gap-2">{o.skills.map(s => <Pill key={s}>{s}</Pill>)}</div></div><div className="flex items-end gap-2 sm:flex-col sm:justify-end"><button onClick={() => toggleSave(o.role)} className={secondaryButton}>{saved.includes(o.role) ? "★ Saved" : "☆ Save"}</button><button className={primaryButton}>Apply now</button></div></div></Panel>)}</div></div>
      <Panel className="h-fit p-4"><SectionTitle icon="📌" title="Saved Opportunities" description={`${saved.length} roles shortlisted`} /><div className="mt-4 space-y-3">{saved.map(role => { const o = opportunities.find(x => x.role === role); return o ? <div key={role} className="rounded-xl border border-slate-800 p-3"><div className="flex items-center gap-2"><BrandLogo company={o.company} size={34} /><div><p className="text-xs font-bold">{o.role}</p><p className="text-[10px] text-slate-400">{o.company} · {o.left}</p></div></div></div> : null; })}{!saved.length && <p className="py-6 text-center text-xs text-slate-500">Save roles to compare them here.</p>}</div></Panel></div>
  </div>;
}
