"use client";
import { useState } from "react";
import { BrandLogo, PageHeader, Panel, Pill, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";
type Company = "Microsoft" | "Amazon" | "TCS" | "Infosys";
const questions = [{ q: "Design a URL shortener", type: "System Design", level: "Medium" }, { q: "Explain process vs thread", type: "Operating Systems", level: "Easy" }, { q: "Longest substring without repeats", type: "DSA", level: "Medium" }, { q: "Tell me about a difficult project", type: "Behavioral", level: "Easy" }];
export default function InterviewsPage() {
  const [company, setCompany] = useState<Company>("Microsoft"); const [saved, setSaved] = useState<string[]>([questions[0].q]);
  return <div className="mx-auto max-w-[1320px]"><PageHeader eyebrow="Preparation Hub" title="How do I prepare?" description="Practice the right questions, learn from company experiences, and walk into every interview with a plan." action={<button className={primaryButton}>🎤 Start mock interview</button>} />
    <Panel className="mb-5 overflow-hidden p-5"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div><Pill tone="violet">NEXT INTERVIEW</Pill><h2 className="mt-4 text-2xl font-extrabold">TCS · Technical Round</h2><p className="mt-2 text-sm text-slate-400">30 June, 10:00 AM · Video interview</p><div className="mt-6 flex gap-3"><button className={primaryButton}>Open preparation plan</button><button className={secondaryButton}>Add to calendar</button></div></div><div className="rounded-2xl border border-violet-500/20 bg-violet-500/5 p-4"><p className="text-xs text-slate-400">READINESS SCORE</p><div className="mt-3 flex items-end gap-3"><strong className="text-5xl">74</strong><span className="mb-1 text-sm text-slate-400">/ 100</span></div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-full w-[74%] rounded-full bg-gradient-to-r from-violet-600 to-sky-400" /></div><p className="mt-3 text-xs text-emerald-400">On track · 5 tasks remaining</p></div></div></Panel>
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{(["Microsoft", "Amazon", "TCS", "Infosys"] as Company[]).map(c => <button key={c} onClick={() => setCompany(c)} className={`${secondaryButton} flex items-center gap-2 ${company === c ? "border-violet-500 bg-violet-500/10" : ""}`}><BrandLogo company={c} size={24} />{c}</button>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.45fr_1fr]"><Panel className="p-5"><SectionTitle icon="📚" title="Question Bank" description={`Curated for ${company} interviews`} action={<button className="text-xs text-violet-400">View all →</button>} /><div className="mt-4 divide-y divide-slate-800">{questions.map((x, i) => <div key={x.q} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-800 text-xs">{i + 1}</span><div className="flex-1"><p className="text-sm font-semibold">{x.q}</p><div className="mt-2 flex gap-2"><Pill>{x.type}</Pill><Pill tone={x.level === "Easy" ? "green" : "amber"}>{x.level}</Pill></div></div><button onClick={() => setSaved(s => s.includes(x.q) ? s.filter(q => q !== x.q) : [...s, x.q])} className="text-xl text-violet-400">{saved.includes(x.q) ? "★" : "☆"}</button></div>)}</div></Panel>
      <div className="space-y-4"><Panel className="p-5"><SectionTitle icon="🏢" title="Company Experiences" description={`Recent ${company} stories`} /><div className="mt-4 space-y-4">{["SDE Intern · Selected", "Cloud role · Round 2"].map((x, i) => <div key={x} className="rounded-xl border border-slate-800 p-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-700">👤</span><div><p className="text-xs font-bold">{i ? "rahul_net" : "ananya_p"}</p><p className="text-[10px] text-slate-500">Shared {i + 2} days ago</p></div></div><p className="mt-3 text-xs font-semibold">{x}</p><p className="mt-1 text-xs leading-5 text-slate-400">Clear fundamentals and project depth mattered more than memorized answers.</p></div>)}</div></Panel><Panel className="p-5"><SectionTitle icon="📝" title="Saved Questions" description={`${saved.length} questions ready to revise`} /><button className={`${secondaryButton} mt-4 w-full`}>Open revision list</button></Panel></div>
    </div>
  </div>;
}
