"use client";
import { useState } from "react";
import { Metric, PageHeader, Panel, Pill, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";
const paths = [
  { icon: "🌐", title: "Networking Roadmap", modules: 12, progress: 62, color: "from-sky-500 to-cyan-400", next: "TCP/IP fundamentals" },
  { icon: "🐧", title: "Linux Roadmap", modules: 10, progress: 45, color: "from-amber-500 to-orange-400", next: "Processes and permissions" },
  { icon: "💬", title: "Communication Roadmap", modules: 8, progress: 75, color: "from-pink-500 to-rose-400", next: "Structured storytelling" },
  { icon: "🎤", title: "Technical Interview Roadmap", modules: 16, progress: 38, color: "from-violet-600 to-indigo-400", next: "Arrays and strings" },
];
export default function LearningPage() {
  const [completed, setCompleted] = useState(false); const [note, setNote] = useState("");
  return <div className="mx-auto max-w-[1320px]"><PageHeader eyebrow="Learning Studio" title="What should I learn?" description="Focused roadmaps built around your current skill gaps and the roles you want next." action={<button className={primaryButton}>＋ Build a learning path</button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Overall progress" value="56%" detail="↑ 8% this month" tone="violet" /><Metric label="Learning streak" value="7 days" detail="Personal best" tone="green" /><Metric label="Hours this week" value="6.5h" detail="1.5h to goal" tone="blue" /></div>
    <div className="mb-5 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Panel className="p-5"><SectionTitle icon="🎯" title="Today&apos;s Focus" description="A small plan that moves your career forward" /><div className="mt-5 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-4"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><Pill tone="violet">NETWORKING · 20 MIN</Pill><h3 className={`mt-3 text-lg font-bold ${completed ? "line-through text-slate-500" : ""}`}>Understand subnetting basics</h3><p className="mt-1 text-xs text-slate-400">Lesson 6 of Networking Roadmap</p></div><button onClick={() => setCompleted(v => !v)} className={completed ? secondaryButton : primaryButton}>{completed ? "✓ Completed" : "Start lesson →"}</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["📖", "Read", "10 min"], ["▶", "Watch", "6 min"], ["✓", "Practice", "4 min"]].map(x => <div key={x[1]} className="rounded-xl border border-slate-800 p-3 text-center"><span>{x[0]}</span><p className="mt-2 text-xs font-bold">{x[1]}</p><p className="text-[10px] text-slate-500">{x[2]}</p></div>)}</div></Panel><Panel className="p-5"><SectionTitle icon="📈" title="Weekly Progress" description="5 of 7 daily goals completed" /><div className="mt-6 flex h-32 items-end justify-between gap-2">{[52, 78, 46, 90, 68, 34, 18].map((h, i) => <div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-gradient-to-t from-violet-700 to-violet-400" style={{ height: `${h}%` }} /><span className="text-[10px] text-slate-500">{"MTWTFSS"[i]}</span></div>)}</div></Panel></div>
    <Panel className="mb-5 p-5"><SectionTitle icon="📚" title="Learning Paths" description="Structured paths for your highest-impact skill gaps" action={<button className="text-xs text-violet-400">Browse library →</button>} /><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{paths.map(p => <div key={p.title} className="rounded-2xl border border-slate-800 bg-black/15 p-4"><span className="text-3xl">{p.icon}</span><h3 className="mt-4 text-sm font-bold">{p.title}</h3><p className="mt-1 text-[11px] text-slate-400">Next: {p.next}</p><div className="mt-5 flex justify-between text-[10px] text-slate-400"><span>{p.modules} modules</span><span>{p.progress}%</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-800"><div className={`h-full rounded-full bg-gradient-to-r ${p.color}`} style={{ width: `${p.progress}%` }} /></div><button className="mt-4 text-xs font-semibold text-violet-400">Continue →</button></div>)}</div></Panel>
    <div className="grid gap-4 lg:grid-cols-2"><Panel className="p-5"><SectionTitle icon="📑" title="Quick Notes" description="Capture what you want to remember" /><textarea value={note} onChange={e => setNote(e.target.value)} className="mt-4 h-28 w-full resize-none rounded-xl border border-slate-700 bg-[#080b10] p-3 text-sm outline-none focus:border-violet-500" placeholder="Write a note from today&apos;s lesson..." /><button className={`${secondaryButton} mt-3`}>Save note</button></Panel><Panel className="p-5"><SectionTitle icon="🏆" title="Certifications" description="Credentials aligned with your goals" /><div className="mt-4 flex items-center gap-4 rounded-xl border border-slate-800 p-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-amber-500/10 text-2xl">☁</span><div className="flex-1"><p className="text-sm font-bold">Azure Fundamentals</p><p className="mt-1 text-xs text-slate-400">Exam readiness · 68%</p></div><button className={secondaryButton}>View plan</button></div></Panel></div>
  </div>;
}
