"use client";
import { useState } from "react";
import { BrandLogo, inputClass, PageHeader, Panel, Pill, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";
type Company = "Microsoft" | "Amazon" | "TCS" | "Infosys";
const seed: { user: string; company: Company; type: string; title: string; body: string; time: string; likes: number }[] = [
  { user: "ananya_p", company: "Microsoft", type: "Interview Experience", title: "Microsoft SDE Intern · Selected", body: "The interview focused on project depth, arrays, and clear communication. The interviewer was supportive—think aloud and clarify assumptions.", time: "2h", likes: 48 },
  { user: "rahul_net", company: "TCS", type: "Salary Shared", title: "Network Engineer · ₹6 LPA", body: "Sharing this to help everyone benchmark. The role includes a six-month training period and a hybrid setup in Mumbai.", time: "4h", likes: 31 },
  { user: "priya_cloud", company: "Amazon", type: "Success Story", title: "From 12 rejections to Amazon", body: "Consistency changed everything. I tracked every mistake, revised weekly, and practiced explaining my projects without jargon.", time: "6h", likes: 126 },
];
export default function CommunityPage() {
  const [posts, setPosts] = useState(seed); const [draft, setDraft] = useState(""); const [liked, setLiked] = useState<number[]>([]);
  const publish = () => { if (!draft.trim()) return; setPosts([{ user: "Himanshi", company: "Infosys", type: "Community Post", title: "A note from my journey", body: draft, time: "now", likes: 0 }, ...posts]); setDraft(""); };
  return <div className="mx-auto max-w-[1180px]"><PageHeader eyebrow="Student Community" title="What are others sharing?" description="Real experiences, salaries, questions, and wins—shared by students, for students. No AI feed. No company feed." action={<button className={primaryButton}>＋ Create post</button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_310px]"><div><Panel className="mb-4 p-4"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-violet-500/15">👩🏻</div><textarea value={draft} onChange={e => setDraft(e.target.value)} className={`${inputClass} min-h-20 resize-none`} placeholder="Share an interview experience, salary, or success story..." /></div><div className="mt-3 flex flex-wrap items-center gap-2"><button className={secondaryButton}>🎤 Experience</button><button className={secondaryButton}>💰 Salary</button><button className={secondaryButton}>🚀 Success story</button><button onClick={publish} className={`${primaryButton} ml-auto`}>Post</button></div></Panel><div className="mb-3 flex gap-2 overflow-x-auto">{["For you", "Interview Experiences", "Salaries", "Success Stories"].map((x, i) => <button key={x} className={`${secondaryButton} ${i === 0 ? "border-violet-500 bg-violet-500/10" : ""}`}>{x}</button>)}</div><div className="space-y-4">{posts.map((p, i) => <Panel key={`${p.user}-${i}`} className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-800">👤</span><div><p className="text-sm font-bold">{p.user}</p><p className="text-[11px] text-slate-500">{p.time} ago · Student verified</p></div><BrandLogo company={p.company} size={34} /><span className="ml-auto">•••</span></div><div className="mt-4"><Pill tone={p.type.includes("Salary") ? "green" : p.type.includes("Success") ? "amber" : "violet"}>{p.type}</Pill><h2 className="mt-3 font-bold">{p.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{p.body}</p></div><div className="mt-4 flex gap-5 border-t border-slate-800 pt-3 text-xs text-slate-400"><button onClick={() => setLiked(x => x.includes(i) ? x.filter(v => v !== i) : [...x, i])} className={liked.includes(i) ? "text-rose-400" : ""}>♥ {p.likes + (liked.includes(i) ? 1 : 0)}</button><button>◯ Reply</button><button>↗ Share</button><button className="ml-auto">☆ Save</button></div></Panel>)}</div></div>
      <aside className="space-y-4"><Panel className="p-4"><SectionTitle icon="🔥" title="Community Pulse" description="This week" /><div className="mt-4 grid grid-cols-2 gap-3">{[["248", "Stories"], ["94", "Salaries"], ["32", "Offers"], ["1.2k", "Helpful votes"]].map(x => <div key={x[1]} className="rounded-xl bg-black/20 p-3"><strong>{x[0]}</strong><p className="text-[10px] text-slate-500">{x[1]}</p></div>)}</div></Panel><Panel className="p-4"><SectionTitle icon="🏢" title="Trending Companies" /><div className="mt-4 space-y-3">{(["Microsoft", "Amazon", "TCS"] as Company[]).map((c, i) => <div key={c} className="flex items-center gap-3"><BrandLogo company={c} size={34} /><div><p className="text-xs font-bold">{c}</p><p className="text-[10px] text-slate-500">{[42, 38, 31][i]} new posts</p></div></div>)}</div></Panel></aside>
    </div>
  </div>;
}
