"use client";
import { useState } from "react";
import { PageHeader, Panel, Pill, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";
export default function ResumePage() {
  const [score, setScore] = useState(81); const [version, setVersion] = useState("Cloud Engineer");
  return <div className="mx-auto max-w-[1240px]"><PageHeader eyebrow="Career Toolkit" title="Is my resume ready?" description="Build role-specific resumes, understand your ATS score, and act on the changes that matter." action={<button className={primaryButton}>＋ New resume</button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><Panel className="min-h-[680px] p-5"><div className="flex items-center justify-between"><SectionTitle icon="📄" title="Resume Builder" description="Cloud Engineer · Last edited 2 mins ago" /><div className="flex gap-2"><button className={secondaryButton}>Preview</button><button className={primaryButton}>Export PDF</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-[210px_1fr]"><div className="space-y-2">{["Personal details", "Summary", "Education", "Experience", "Projects", "Skills", "Certifications"].map((x, i) => <button key={x} className={`flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-xs ${i === 4 ? "bg-violet-500/15 text-violet-300" : "text-slate-400 hover:bg-white/5"}`}><span>{i < 3 ? "✓" : "○"} &nbsp;{x}</span><span>›</span></button>)}</div><div className="rounded-2xl bg-white p-7 text-slate-900 shadow-2xl"><div className="border-b border-slate-200 pb-4"><h2 className="text-2xl font-extrabold">Himanshi Sharma</h2><p className="text-sm text-slate-600">Cloud & Network Engineering Student</p><p className="mt-2 text-[10px] text-slate-500">himanshi@email.com · Bengaluru · linkedin.com/in/himanshi</p></div><div className="mt-5"><h3 className="text-xs font-extrabold uppercase tracking-wider text-violet-700">Projects</h3><div className="mt-3"><div className="flex justify-between"><strong className="text-sm">Cloud Monitoring Dashboard</strong><span className="text-xs text-slate-500">2026</span></div><p className="mt-1 text-xs leading-5 text-slate-600">Built a real-time monitoring dashboard using Azure services, Python, and containerized workloads.</p></div><div className="mt-4"><div className="flex justify-between"><strong className="text-sm">Network Automation Toolkit</strong><span className="text-xs text-slate-500">2025</span></div><p className="mt-1 text-xs leading-5 text-slate-600">Automated configuration validation and reduced manual review time by 40%.</p></div></div><div className="mt-5"><h3 className="text-xs font-extrabold uppercase tracking-wider text-violet-700">Skills</h3><p className="mt-2 text-xs text-slate-600">Azure · Linux · Python · Networking · Docker · SQL</p></div></div></div></Panel>
      <aside className="space-y-4"><Panel className="p-5"><SectionTitle icon="🎯" title="ATS Score" description="For Cloud Intern roles" /><div className="mx-auto mt-5 grid h-36 w-36 place-items-center rounded-full bg-[conic-gradient(#22c55e_0_81%,#28303b_81%)]"><div className="grid h-28 w-28 place-items-center rounded-full bg-[#0d1117]"><div className="text-center"><strong className="text-4xl">{score}</strong><p className="text-[10px] text-slate-500">Excellent</p></div></div></div><button onClick={() => setScore(s => Math.min(96, s + 3))} className={`${secondaryButton} mt-5 w-full`}>Re-scan resume</button></Panel><Panel className="p-5"><SectionTitle icon="💡" title="Suggestions" description="3 high-impact changes" /><div className="mt-4 space-y-3">{[["Add measurable outcomes", "Projects", "amber"], ["Include Kubernetes keyword", "Skills", "violet"], ["Shorten professional summary", "Summary", "green"]].map(([x, y, tone]) => <div key={x} className="rounded-xl border border-slate-800 p-3"><Pill tone={tone as "amber" | "violet" | "green"}>{y}</Pill><p className="mt-2 text-xs font-semibold">{x}</p></div>)}</div></Panel><Panel className="p-5"><SectionTitle icon="📌" title="Resume Versions" /><select value={version} onChange={e => setVersion(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-700 bg-[#090c12] p-3 text-xs"><option>Cloud Engineer</option><option>Network Engineer</option><option>General Campus</option></select><p className="mt-3 text-xs text-slate-500">Editing: {version}</p></Panel></aside>
    </div>
  </div>;
}
