"use client";
import { useState } from "react";
import Image from "next/image";
import { inputClass, PageHeader, Panel, primaryButton, secondaryButton, SectionTitle } from "@/components/ui/Workspace";
const Toggle = ({ on, set }: { on: boolean; set: () => void }) => <button onClick={set} className={`flex h-6 w-11 items-center rounded-full p-1 transition ${on ? "justify-end bg-violet-600" : "justify-start bg-slate-700"}`}><span className="h-4 w-4 rounded-full bg-white" /></button>;
export default function SettingsPage() {
  const [email, setEmail] = useState(true); const [deadline, setDeadline] = useState(true); const [community, setCommunity] = useState(false); const [privateProfile, setPrivateProfile] = useState(false);
  return <div className="mx-auto max-w-[1050px]"><PageHeader eyebrow="Preferences" title="How do I manage my account?" description="Keep your profile, notifications, privacy, and CareerOS data under your control." />
    <div className="grid gap-5 lg:grid-cols-[220px_1fr]"><Panel className="h-fit p-3"><nav className="space-y-1">{["👤 Profile", "◐ Theme", "🔔 Notifications", "🔒 Privacy", "⚙ Account", "↥ Export Data"].map((x, i) => <button key={x} className={`w-full rounded-xl px-3 py-3 text-left text-xs ${i === 0 ? "bg-violet-500/15 font-bold text-violet-300" : "text-slate-400 hover:bg-white/5"}`}>{x}</button>)}</nav></Panel><div className="space-y-5"><Panel className="p-5"><SectionTitle icon="👤" title="Profile" description="Your public student identity" /><div className="mt-5 flex items-center gap-4"><div className="relative h-20 w-20 overflow-hidden rounded-full border-2 border-violet-500"><Image src="/avatar/mentor.png" alt="Profile" fill className="object-cover" /></div><div><button className={secondaryButton}>Change photo</button><p className="mt-2 text-[10px] text-slate-500">PNG or JPG · Max 5 MB</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Full name", "Himanshi Sharma"], ["Email", "himanshi@email.com"], ["College", "SkillStack Institute"], ["Target role", "Cloud Engineer"]].map(([label, value]) => <label key={label} className="text-xs text-slate-400">{label}<input className={`${inputClass} mt-2`} defaultValue={value} /></label>)}</div><button className={`${primaryButton} mt-5`}>Save changes</button></Panel>
      <Panel className="p-5"><SectionTitle icon="◐" title="Theme" description="Choose how CareerOS looks" /><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Dark", "Midnight", "System"].map((x, i) => <button key={x} className={`rounded-xl border p-4 text-left text-xs ${i === 0 ? "border-violet-500 bg-violet-500/10" : "border-slate-700"}`}><span className={`mb-3 block h-16 rounded-lg ${i === 0 ? "bg-[#070a0f]" : i === 1 ? "bg-[#0b1020]" : "bg-gradient-to-r from-white to-slate-900"}`} />{x}</button>)}</div></Panel>
      <Panel className="p-5"><SectionTitle icon="🔔" title="Notifications" description="Decide what deserves your attention" /><div className="mt-4 divide-y divide-slate-800">{[["Email updates", "Weekly career summary and activity", email, () => setEmail(v => !v)], ["Deadline reminders", "Applications, assessments and interviews", deadline, () => setDeadline(v => !v)], ["Community activity", "Replies and helpful votes", community, () => setCommunity(v => !v)]].map(([title, desc, on, set]) => <div key={title as string} className="flex items-center justify-between py-4"><div><p className="text-sm font-semibold">{title as string}</p><p className="mt-1 text-xs text-slate-500">{desc as string}</p></div><Toggle on={on as boolean} set={set as () => void} /></div>)}</div></Panel>
      <Panel className="p-5"><SectionTitle icon="🔒" title="Privacy & Data" description="Your data stays yours" /><div className="mt-4 flex items-center justify-between"><div><p className="text-sm font-semibold">Private profile</p><p className="mt-1 text-xs text-slate-500">Hide your activity from other students</p></div><Toggle on={privateProfile} set={() => setPrivateProfile(v => !v)} /></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-800 pt-5"><button className={secondaryButton}>Export all data</button><button className={secondaryButton}>Manage connected accounts</button><button className="rounded-xl border border-rose-500/30 px-4 py-2.5 text-xs text-rose-400">Delete account</button></div></Panel></div></div>
  </div>;
}
